/**
 * Type definitions for Gym Workout Logger
 * Based on requirements specification
 */

export interface Set {
  setNumber: number;
  weight: number;
  reps: number;
  rpe: number;      // Rate of Perceived Exertion: 1-100, default 80
  restTime: number; // Rest time in seconds, default 60
}

export interface Exercise {
  exerciseName: string;
  notes: string;
  sets: Set[];
}

export interface Workout {
  id?: number;              // Auto-generated by IndexedDB
  date: string;             // ISO date string (YYYY-MM-DD)
  startTime: string;        // ISO timestamp
  endTime: string;          // ISO timestamp
  duration: number;         // Duration in minutes
  notes: string;
  exercises: Exercise[];
}

export interface ExerciseLibraryItem {
  id?: number;              // Auto-generated by IndexedDB
  name: string;
  lastUsed: string;         // ISO timestamp
  useCount: number;
}

export type WeightUnit = 'lbs' | 'kg';

export interface AppSettings {
  weightUnit: WeightUnit;
  defaultRPE: number;
  defaultRestTime: number;
}

// Default values as constants
export const DEFAULT_SETTINGS: AppSettings = {
  weightUnit: 'lbs',
  defaultRPE: 80,
  defaultRestTime: 60,
};

// Starter exercises as specified in requirements
export const STARTER_EXERCISES: string[] = [
  // Barbell
  'Bench Press',
  'Squat',
  'Deadlift',
  'Overhead Press',
  'Barbell Row',
  'Romanian Deadlift',
  // Dumbbell
  'Dumbbell Press',
  'Dumbbell Row',
  'Dumbbell Curl',
  'Dumbbell Fly',
  // Bodyweight
  'Pull-ups',
  'Chin-ups',
  'Dips',
  'Push-ups',
  // Machines
  'Lat Pulldown',
  'Cable Row',
  'Leg Press',
  'Leg Curl',
  'Leg Extension',
];
