/**
 * Type definitions for Gym Workout Logger
 * Based on requirements specification
 */

export interface Set {
  setNumber: number;
  weight?: number;      // Optional for bodyweight/cardio exercises
  reps?: number;        // Optional for cardio exercises
  rpe?: number;         // Rate of Perceived Exertion: 1-100, default 80 (optional for bodyweight/cardio)
  restTime?: number;    // Rest time in seconds, default 60 (optional for cardio)
  duration?: number;    // Duration in seconds (for cardio exercises)
}

export interface Exercise {
  exerciseName: string;
  notes: string;
  sets: Set[];
}

export interface Workout {
  id?: number;              // Auto-generated by IndexedDB
  name?: string;            // Optional workout name (e.g., "Back and Biceps")
  date: string;             // ISO date string (YYYY-MM-DD)
  startTime: string;        // ISO timestamp
  endTime: string;          // ISO timestamp
  duration: number;         // Duration in minutes
  notes: string;
  exercises: Exercise[];
}

export type ExerciseCategory = 'Push' | 'Pull' | 'Legs' | 'Arms' | 'Core' | 'Other';

export type ExerciseType = 'strength' | 'cardio' | 'bodyweight';

export interface ExerciseVideoLink {
  title: string;
  url: string;
}

export interface ExerciseLibraryItem {
  id?: number;              // Auto-generated by IndexedDB
  name: string;
  category: ExerciseCategory;
  type: ExerciseType;       // Exercise type determines which fields to track
  lastUsed: string;         // ISO timestamp
  useCount: number;
  links: ExerciseVideoLink[];  // Video links for exercise form/technique
}

export type WeightUnit = 'lbs' | 'kg';

export interface AppSettings {
  weightUnit: WeightUnit;
  defaultRPE: number;
  defaultRestTime: number;
}

// Default values as constants
export const DEFAULT_SETTINGS: AppSettings = {
  weightUnit: 'lbs',
  defaultRPE: 80,
  defaultRestTime: 60,
};

// Screen types for navigation
export type Screen = 'home' | 'workout' | 'history' | 'settings' | 'exercise-library' | 'edit-workout' | 'templates';

// Workout template interface
export interface WorkoutTemplate {
  id?: number;
  name: string;                    // e.g., "Push Day"
  description: string;             // e.g., "Chest, shoulders, triceps"
  exercises: string[];             // Just exercise names, no sets
  isStarter: boolean;              // True for pre-built templates
  useCount: number;                // Track usage for sorting
  lastUsed: string;                // ISO timestamp
  createdAt: string;               // ISO timestamp
}

// Starter exercises as specified in requirements
export const STARTER_EXERCISES: Array<{ name: string; category: ExerciseCategory; type: ExerciseType }> = [
  // Push exercises
  { name: 'Bench Press', category: 'Push', type: 'strength' },
  { name: 'Overhead Press', category: 'Push', type: 'strength' },
  { name: 'Dumbbell Press', category: 'Push', type: 'strength' },
  { name: 'Dumbbell Fly', category: 'Push', type: 'strength' },
  { name: 'Dips', category: 'Push', type: 'bodyweight' },
  { name: 'Push-ups', category: 'Push', type: 'bodyweight' },

  // Pull exercises
  { name: 'Deadlift', category: 'Pull', type: 'strength' },
  { name: 'Barbell Row', category: 'Pull', type: 'strength' },
  { name: 'Dumbbell Row', category: 'Pull', type: 'strength' },
  { name: 'Pull-ups', category: 'Pull', type: 'bodyweight' },
  { name: 'Chin-ups', category: 'Pull', type: 'bodyweight' },
  { name: 'Lat Pulldown', category: 'Pull', type: 'strength' },
  { name: 'Cable Row', category: 'Pull', type: 'strength' },

  // Leg exercises
  { name: 'Squat', category: 'Legs', type: 'strength' },
  { name: 'Romanian Deadlift', category: 'Legs', type: 'strength' },
  { name: 'Leg Press', category: 'Legs', type: 'strength' },
  { name: 'Leg Curl', category: 'Legs', type: 'strength' },
  { name: 'Leg Extension', category: 'Legs', type: 'strength' },

  // Arm exercises
  { name: 'Dumbbell Curl', category: 'Arms', type: 'strength' },
];

// Starter workout templates
export const STARTER_TEMPLATES: Array<{ name: string; description: string; exercises: string[] }> = [
  {
    name: 'Push Day',
    description: 'Chest, shoulders, triceps',
    exercises: ['Bench Press', 'Overhead Press', 'Dumbbell Fly', 'Dips'],
  },
  {
    name: 'Pull Day',
    description: 'Back and biceps',
    exercises: ['Deadlift', 'Pull-ups', 'Barbell Row', 'Dumbbell Curl'],
  },
  {
    name: 'Leg Day',
    description: 'Lower body',
    exercises: ['Squat', 'Romanian Deadlift', 'Leg Press', 'Leg Curl'],
  },
  {
    name: 'Upper Body',
    description: 'Full upper body workout',
    exercises: ['Bench Press', 'Barbell Row', 'Overhead Press', 'Pull-ups', 'Dumbbell Curl', 'Dips'],
  },
  {
    name: 'Lower Body',
    description: 'Full lower body workout',
    exercises: ['Squat', 'Romanian Deadlift', 'Leg Press', 'Leg Curl', 'Leg Extension'],
  },
  {
    name: 'Full Body',
    description: 'Complete full body workout',
    exercises: ['Squat', 'Bench Press', 'Deadlift', 'Pull-ups', 'Overhead Press'],
  },
];
